name: wechooser
version: 1

libraries:
- name: "django"
  version: "1.5"

handlers:
- url: /static
  static_dir: static

cron:
- description: cron_test
  url: /duiba/alarm
  schedule: "*/1 * * * *"